<?php
return array (
  'cron_entry.cleanUpDaily' => 'Daily Clean Up',
  'cron_entry.cleanUpHourly' => 'Hourly Clean Up',
  'cron_entry.dailyStats' => 'Record Daily Statistics',
  'cron_entry.deleteExpiredBans' => 'Delete Expired Bans',
  'cron_entry.downgradeExpired' => 'Downgrade Expired User Upgrades',
  'cron_entry.emailBounce' => 'Process Email Bounces',
  'cron_entry.expireTempUserChanges' => 'Expire Temporary User Changes',
  'cron_entry.feeder' => 'Feeder',
  'cron_entry.fileCheck' => 'Perform file health check',
  'cron_entry.forumStatistics' => 'Cập nhật thống kê diễn đàn',
  'cron_entry.memberStatsCache' => 'Cập nhật bộ nhớ đệm thống kê thành viên',
  'cron_entry.run_successfully' => 'Cron entry run successfully.',
  'cron_entry.sitemap' => 'Cập nhật Sitemap',
  'cron_entry.trophy' => 'Cập nhật danh hiệu thành viên',
  'cron_entry.userGroupPromotions' => 'User Group Promotions',
  'cron_entry.views' => 'Update View Counters',
  'cron_entry.warningExpiry' => 'Xử lý hết hạn cảnh báo',
);