<?php
return array (
  'admin_permission.addOn' => 'Quản lý Tiện ích',
  'admin_permission.advertising' => 'Quản lý quảng cáo',
  'admin_permission.attachment' => 'Quản lý tập tin đính kèm',
  'admin_permission.ban' => 'Manage bans',
  'admin_permission.bbCodeSmilie' => 'Manage BB codes and smilies',
  'admin_permission.cron' => 'Manage cron entries',
  'admin_permission.help' => 'Manage help',
  'admin_permission.import' => 'Nhập dữ liệu',
  'admin_permission.language' => 'Manage languages and phrases',
  'admin_permission.navigation' => 'Manage navigation',
  'admin_permission.node' => 'Quản lý chuyên mục',
  'admin_permission.notice' => 'Quản lý thông báo',
  'admin_permission.option' => 'Quản lý tùy chọn',
  'admin_permission.payment' => 'Quản lý các nhà cung cấp dịch vụ',
  'admin_permission.rebuildCache' => 'Cập nhật bộ nhớ đệm',
  'admin_permission.style' => 'Quản lý giao diện, thuộc tính giao diện và mẫu',
  'admin_permission.tags' => 'Quản lý từ khóa',
  'admin_permission.thread' => 'Manage threads and posts',
  'admin_permission.trophy' => 'Quản lý danh hiệu',
  'admin_permission.user' => 'Quản lý thành viên và Kiểm duyệt viên',
  'admin_permission.userField' => 'Quản lý trường tùy chỉnh thành viên',
  'admin_permission.userGroup' => 'Quản lý Nhóm thành viên',
  'admin_permission.userUpgrade' => 'Quản lý nâng cấp thành viên',
  'admin_permission.viewLogs' => 'Xem nhật ký',
  'admin_permission.viewStatistics' => 'Xem số liệu thống kê',
  'admin_permission.warning' => 'Quản lý cảnh báo',
  'admin_permission.widget' => 'Manage widgets',
);