<?php
return array (
  'option_group.acp' => 'Admin Control Panel',
  'option_group.alerts' => 'User Alerts',
  'option_group.appearance' => 'Appearance',
  'option_group.attachments' => 'Attachments',
  'option_group.basicBoard' => 'Thông tin diễn đàn cơ bản',
  'option_group.boardActive' => 'Diễn đàn hoạt động',
  'option_group.censoringOptions' => 'Censoring',
  'option_group.debug' => 'Debug Options',
  'option_group.discourager' => 'User Discouragement and Discipline',
  'option_group.discussionOptions' => 'Threads,  Discussions and Conversations',
  'option_group.emailOptions' => 'Email Options',
  'option_group.imageLinkProxy' => 'Image and link proxy',
  'option_group.logging' => 'Logging Options',
  'option_group.mediaEmbedding' => 'Media embedding',
  'option_group.messageOptions' => 'Messages',
  'option_group.newsfeed' => 'News Feed',
  'option_group.nodeList' => 'Node & Forum List',
  'option_group.performance' => 'Performance',
  'option_group.searchOptions' => 'Search Options',
  'option_group.seo' => 'Search Engine Optimization (SEO)',
  'option_group.serviceProviders' => 'External Service Providers',
  'option_group.sharing' => 'Sharing',
  'option_group.sitemap' => 'XML Sitemap Generation',
  'option_group.spam' => 'Spam Management',
  'option_group.stats' => 'Thống kê và Chỉ số',
  'option_group.tagging' => 'Content Tagging',
  'option_group.users' => 'User Options',
  'option_group.usersAndRegistration' => 'User Registration',
);